import { ThemeProvider } from '@/components/providers/theme-provider'
import { languages } from '@/i18n/settings'
import { localization } from '@/lib/utils'
import { ChildProp } from '@/types'
import { ClerkProvider } from '@clerk/nextjs'
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin'
import type { Metadata } from 'next'
import { extractRouterConfig } from 'uploadthing/server'

import { Roboto, Space_Grotesk as SpaceGrotesk } from 'next/font/google'
import { Toaster } from 'sonner'
import { ourFileRouter } from './api/uploadthing/core'
import './globals.css'
const roboto = Roboto({
	subsets: ['latin', 'cyrillic'],
	weight: ['100', '300', '400', '500', '700', '900'],
	variable: '--font-roboto',
})

const spaceGrotesk = SpaceGrotesk({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['latin'],
	variable: '--font-space-grotesk',
})

export async function generateStaticParams() {
	return languages.map(lng => ({ lng }))
}

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: '/logo.svg',
}
interface Props extends ChildProp {
	params: { lng: string }
}
export default function RootLayout({ children, params: { lng } }: Props) {
	const local = localization(lng)
	return (
		<ClerkProvider localization={local}>
			<html lang={lng} suppressHydrationWarning>
				<body
					className={`${roboto.variable} ${spaceGrotesk.variable} overflow-x-hidden`}
				>
					<ThemeProvider
						attribute='class'
						defaultTheme='system'
						enableSystem
						disableTransitionOnChange
					>
						<NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
						{children}
						<Toaster position='top-center' />
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	)
}
